version: 0.1
component: build
timeoutInSeconds: 10000
shell: bash
env:
  exportedVariables:
     - BUILDRUN_HASH

steps:
  - type: Command
    name: "Define a version for artifact"
    timeoutInSeconds: 40
    command: |
      export BUILDRUN_HASH=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7`
      echo "BUILDRUN_HASH: " $BUILDRUN_HASH

  - type: Command
    name: "Create Docker Image"
    timeoutInSeconds: 650
    command: |
      cd pythonfn/
      fn build -v
      image=$(docker images | grep tweet_retriever | awk -F ' ' '{print $3}') ; docker tag $image pythonfn


outputArtifacts:
  - name: output01
    type: DOCKER_IMAGE
    location: pythonfn:latest